stb-kodi-vuultimo4k: Fix build
ERROR: stb-kodi-vuultimo4k-21.0+gitr-r0 do_package_qa: QA Issue: /usr/lib/kodi/kodi-stb contained in package stb-kodi-vuultimo4k
requires libEGL.so, but no providers found in RDEPENDS:stb-kodi-vuultimo4k? [file-rdeps]