vuplus-blindscan-utils-mipsel: Replace 'virtual/' with 'wirtual-'
To fix:
ERROR: Nothing RPROVIDES 'virtual-blindscan-dvbc' (but /home/hains/test-images/openpli-oe-core/meta-openpli/
recipes-openpli/enigma2/enigma2.bb RDEPENDS on or otherwise requires it)

https://git.openembedded.org/openembedded-core/commit/?h=scarthgap&id=f673d3d239799fb1ab50f4aa5d44187666aa0cd7