libgles.inc: Don't copy egl/opengl header files
To fix build Kodi.

/build/tmp/work/vuultimo4k-oe-linux-gnueabi/stb-kodi-vuultimo4k/21.0+gitr/recipe-sysroot/usr/include/EGL/
eglplatform.h:128:10: error: 'X11/Xlib.h' file not found [clang-diagnostic-error]
|   128 | #include <X11/Xlib.h>
|       |          ^~~~~~~~~~~~

Sync more with OE-A, which does this this copy thing neither.